name: Tag Release

on:
  push:
    branches: [main]
    paths: [pyproject.toml]

permissions:
  contents: write

jobs:
  call-tag-release:
    uses: django-mvp/shared/.github/workflows/tag-release.yml@{{ cookiecutter._shared_tag }}
    secrets:
      RELEASE_TOKEN: {% raw %}${{ secrets.RELEASE_TOKEN }}{% endraw %}
